AdilBank/Models/Account.cs
namespace AdilBank.Models
{
    public class Account
    {
        public string Name { get; set; }
        public double Balance { get; set; }
        public Customer Customer { get; set; }
    }
}

AdilBank/Models/Customer.cs
namespace AdilBank.Models
{
    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

AdilBank/Models/ErrorViewModel.cs
using System;

namespace AdilBank.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AdilBank/Controllers/HomeController.cs
using AdilBank.Models;
using AdilBank.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AdilBank.Controllers
{
    public class HomeController : Controller
    {
        private readonly BankRepository _bankRepository;

        public HomeController(BankRepository bankRepository)
        {
            _bankRepository = bankRepository;
        }

        public IActionResult Index()
        {
            return View(_bankRepository);
        }  

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AdilBank/Controllers/TransactionController.cs
using AdilBank.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace AdilBank.Controllers
{
    public class TransactionController : Controller
    {
        private readonly BankRepository _bankRepository;

        public TransactionController(BankRepository bankRepository)
        {
            _bankRepository = bankRepository;
        }

        public IActionResult Index()
        {
            return View(_bankRepository);
        }

        [HttpPost]
        public IActionResult Index(string transactionType, double accountBalance, double amount, string accountName, string fromAccount, string targetAccount)
        {
            double sum; 

            if (transactionType == "Uttag")
            {
                if (amount > accountBalance)
                {
                    ViewBag.Message = "Värdet är för högt!";
                    return View(_bankRepository);
                }
                _bankRepository.Withdraw(amount, accountName);
                sum = accountBalance - amount;
                ViewBag.Message = $"Det har dragits {amount} från kontot {accountName}, saldo är nu {sum}";
                return View(_bankRepository);
            }
            else if (transactionType == "Insättning")
            {
                _bankRepository.Deposit(amount, accountName);
                sum = accountBalance + amount;
                ViewBag.Message = $"Det har lagts till {amount} till kontot {accountName}, saldo är nu {sum}";
                return View(_bankRepository);
            }
            else
            {
                ViewBag.Message = "Något gick snett";
                return View();
            }
        }
    }
}

AdilBank/Controllers/TransferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AdilBank.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace AdilBank.Controllers
{
    public class TransferController : Controller
    {
        private readonly BankRepository _bankRepository;

        public TransferController(BankRepository bankRepository)
        {
            _bankRepository = bankRepository;
        }

        public IActionResult Index()
        {
            return View(_bankRepository);
        }

        [HttpPost]
        public IActionResult Index(string transactionType, double amount, string fromAccount, string targetAccount)
        {
            var withdrawalAccount = _bankRepository.Accounts.FirstOrDefault(account => account.Name == fromAccount);

            if (withdrawalAccount != null)
            {
                var result = _bankRepository.Transfer(amount, fromAccount, targetAccount);
                if (result == false)
                {
                    ViewBag.Message = $"Konto {fromAccount} har inte tillräckligt med pengar";
                    return View(_bankRepository);
                }
                else
                {
                    ViewBag.Message = $"{amount} har överförts från {fromAccount} till {targetAccount}";
                    return View(_bankRepository);
                }
            }
            else
            {
                ViewBag.Message = $"Kontot finns ej";
                return View(_bankRepository);
            }
        }
    }
}

AdilBank/Views/Home/Index.cshtml
@model AdilBank.Repositories.BankRepository

@{
    ViewData["Title"] = "Adils Bank";
}

<div>
    <table>
        <tbody>
        <tr>
            <th>Customer Name</th>
            <th>Account Number</th>
            <th>Account Balance</th>
        </tr>

        @foreach (var account in Model.Accounts)
        {
            <tr>
                <td>@account.Customer.Name</td>
                <td>@account.Name</td>
                <td>@account.Balance</td>
            </tr>
        }

        </tbody>
    </table>
</div>

<style>
    table {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #ddd;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    tr:hover {
        background-color: #ddd;
    }

    th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #4CAF50;
        color: white;
    }
</style>

AdilBank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Adils Bank</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Transaction" asp-action="Index">Transaction</a></li>
                    <li><a asp-area="" asp-controller="Transfer" asp-action="Index">Föra över</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - AdilBank</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

AdilBank/Views/Transaction/Index.cshtml
@model AdilBank.Repositories.BankRepository

<table>
    <tr>
        <th>
            Konto
        </th>
        <th>
            Saldo
        </th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var account in Model.Accounts)
    {
        <form asp-controller="Transaction" asp-action="Index" method="post">
            <tr>
                <td><input type="hidden" name="accountName" value="@account.Name" />@account.Name</td>
                <td><input type="hidden" name="accountBalance" value="@account.Balance" />@account.Balance</td>
                <td><input type="text" name="amount" /></td>
                <td><input type="submit" class="btn btn-default" value="Uttag" name="transactionType" /></td>
                <td><input type="submit" class="btn btn-success" value="Insättning" name="transactionType" /></td>
                <td></td>
            </tr>
        </form>
    }
</table>
<h4>@ViewBag.Message</h4>


<style>
    table {
         font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
         border-collapse: collapse;
         width: 100%;
     }

    td, th {
        border: 1px solid #ddd;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    tr:hover {
        background-color: #ddd;
    }

    th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #4CAF50;
        color: white;
    }
</style>

AdilBank/Views/Transfer/Index.cshtml
@model AdilBank.Repositories.BankRepository


<div class="row">
    <form asp-controller="Transfer" asp-action="Index" method="post">
        <h3>Betala till andra</h3><br />
        <label>Från konto</label><br />
        <input type="text" name="fromAccount" /><br /><br />
        <label>Till konto</label><br />
        <input type="text" name="targetAccount" /><br /><br />
        <label>Summa</label><br />
        <input type="text" name="amount" /><br /><br />
        <input type="submit" class="btn btn-success" value="Skicka" name="transactionType" />
    </form>
</div>
<br />
<h4>@ViewBag.Message</h4>


<table>
    <tr>
        <th>
            Konto
        </th>
        <th>
            Saldo
        </th>

    </tr>
    @foreach (var account in Model.Accounts)
    {
            <tr>
                <td><input type="hidden" name="accountName" value="@account.Name" />@account.Name</td>
                <td><input type="hidden" name="accountBalance" value="@account.Balance" />@account.Balance</td>
            </tr>
    }
</table>

<style>
    table {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #ddd;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    tr:hover {
        background-color: #ddd;
    }

    th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #4CAF50;
        color: white;
    }
</style>